### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by finfan222** [Fin-Ex/finex-server#4]
Условия:
1. Прототипы должны лежать в sql и подгружаться оттуда же
2. Прототипы должны быть максимально абстрактными
3. Прототипы действую как шаблоны и являются part-of-object

# Рассмотрение каждой части отдельно и мысли вслух
###### Прототипы должны лежать в sql и подгружаться оттуда же
Основная фича, позволяющая брать прототипы из .sql частей. БД даёт нам возможность менять их динамически - если это необходимо во время игрового процесса, отсюда мы получаем след. возможности:
1. Увеличение того или иного параметра в режиме runtime, например если спавним моба "кабан" его параметры могут отличаться от "кабан" в ночное время без манипуляций в коде, т.е. .sql в таблицах может рандомно менять значения, а рнадомизатор можно уже крепить самому выведя для него API
2. Игровой персонаж имеет так же прототип, а значит, что в любой момент времени, мы сможем получить любые параметры из любого куска прототипа (если такой относим к персонажу в текущей игре любого типа)

Как я представляю реализацию модели для БД под прототипы:

### Parameters & Appearance
![image](https://user-images.githubusercontent.com/13859076/135261571-7dab6142-1957-420b-937d-f3973249f65f.png)

![image](https://user-images.githubusercontent.com/13859076/135261723-0ad59b4b-5a26-48b9-b56d-2b2171ba05ad.png)

![image](https://user-images.githubusercontent.com/13859076/135261749-527d53d1-2cb6-4825-a583-e7f77c2814de.png)

Пока ещё не понимаю как сделать так, чтобы в игре предоставляемой юзером например на UE4 он закладывал дату  скажем параметров:
ATK
DEF
SPD

а в базе таких параметров просто нет, он получается сможет внести их как на скринах выше. Он так же сможет использовать 1 DB для своей игры но разных серверов например, что позволит ему уже заранее иметь загатовки как сервера А так и сервера Б.
Например 1 игра 2 обновления, MyGame ver1, MyGame ver2 - неудачная, но является актуалом клиента. Можно будет запустить 2 сервера своей игры на разхных обновах, при этом никто кроме (возможно самого клиента игры) не будет мешать нам переиспользовать шаблоны с прошлых обнов.

А возможно это всё хуйня.

### Сборка и Шаблонизация
У нас получается что таблицы с элементами прототипирования являются частями полноценного прототипа, нам остаётся лишь собрать прототип либо в режиме runtime либо через промежуточную таблицу sql, которая является полноценныым прототипом под game-object. См. пример ниже.

![image](https://user-images.githubusercontent.com/13859076/135263560-1b79ffa6-1ed4-4788-990a-d51a728da88f.png)

Таким образом можно коннектить всё что угодно (вывести в конфигурацию эволюций для клиента) и добавлять любые будущие фичи для будущих прототипов этой игры, условия ношения эквипы как част ьпрототипа, арзмер члена как часть прототипа и т.д.

Сборка шаблона осуществляется в коде и построена очевидно на датах (в моём видении)

![image](https://user-images.githubusercontent.com/13859076/135264103-ee0edf72-2d23-4ac2-a241-d82423b9b28b.png)

**Comment by zcxv** [comment]
Основная фича прототипов в БД, то что у тебя данные неразрывны. Другими словами, твои связи не исчезают на каком-то ID, а ведут непосредственно к данным, в том числе полу-статическим/справочным.

**Comment by finfan222** [comment]
Бля значит всё неправильно получается

**Comment by zcxv** [comment]
У нас уже есть разметки прототипов, т.е. на какие игровые объекты какие компоненты накладываются, остается лишь добавить сюда данные.
![image](https://user-images.githubusercontent.com/1573467/135265476-50c4e4ff-27b2-4485-84ad-30fe13efd079.png)

Моя идея заключается в том, чтобы обыграть это одной дополнительной таблицей, которая будет связана с `game_object_component_prototypes`. Драфт:
![image](https://user-images.githubusercontent.com/1573467/135266328-5184bdad-0ae0-40d6-8d00-7df09be1e592.png)

![image](https://user-images.githubusercontent.com/1573467/135266401-b8254620-8404-4e3a-b014-313d9ef9aa9d.png)

Так как это полу-статические данные (справочные), то их изменения в рантайме не ожидается, ввиду чего можно засунуть все это дело в json, при этом сохранив возможность ориентации внутри, например:
```SQL
select 
	component_data.data->'hp' hp, 
	component_data.data->'maxHp' max_hp, 
	component_data.data->'someObject'->>'field' some_field
from game_object_component_prototype_data component_data 
join game_object_component_prototypes component on component.id = component_data.component_id 
join game_object_prototypes game_object on game_object.id = component.prototype_id
where game_object.id = 1
```

Таким образом прототипы можно генерировать на стороне клиента, либо, вообще в отдельном тулсете в виде json и в последствии, через эволюцию, загружать/обновлять их.
Маппинг с JSON в модель должен проходить хорошо и гладко, для специфичных типов можно написать свои сериализаторы/десериализаторы.
```

**Comment by Empericall** [comment]
1. Могут ли некоторые компоненты быть переиспользованы в рамках разных прототипов?

Например:
```
----------------------------------
| component_id |       data      |
----------------------------------
|      1       | {"key1":"val1"} |
|      2       | {"key2":"val2"} |
----------------------------------
```

```
-------------------------------
| prototype_id | component_id |
-------------------------------
|      1       |      1       | <--- ???
|      1       |      2       |
|      2       |      1       | <--- ???
-------------------------------
```

- Если да, то необходимо отделять связь между прототипами и компонентами за рамки декларативной таблицы компонентов.
- Если нет, то можно связывать прототипы с компонентами в рамках одной таблицы (декларативной).

P.S. Моё мнение: да, могут быть.

2. Может ли возникать наличие нескольких записей с json данными для этого и того же компонента.

Например:
```
----------------------------------
| component_id |       data      |
----------------------------------
|      1       | {"key1":"val1"} | <---- ???
|      1       | {"key11":"val1"}| <---- ???
|      2       | {"key2":"val2"} |
|      3       | {"key3":"val3"} |
----------------------------------
```

- Если да, то необходимо вынести component_data в отдельную таблицу, а со стороны сервисной части мерджить полученные
мапы (но трудно представить что будет с большой вложенностью одновременно с наличием комплексных типов).
- Если нет, то колонка component_data может находиться в таблице components.

P.S. Моё мнение: в этом вопросе здесь всё зависит от желания заёбываться с логикой мерджа N-ного количества
таких возможных записей. Мне кажется будет проще предусмотреть этот момент в тулинге, который будет необходим
для генерации эволюций (если он будет выполнен в виде api, то придумывать даже ничего не придётся) и crud части
персистенции (но я могу ошибаться на счёт того что 1ый вариант является проблемным).
