### ISSUE TITLE
Доработка прототипов

### ISSUE THREAD

**Issue by zcxv** [Fin-Ex/finex-server#9]
**References**: #4 

**Описание**:
У нас уже есть разметки прототипов, т.е. на какие игровые объекты какие компоненты накладываются, остается лишь добавить сюда данные.
![image](https://user-images.githubusercontent.com/1573467/135265476-50c4e4ff-27b2-4485-84ad-30fe13efd079.png)

Моя идея заключается в том, чтобы обыграть это одной дополнительной таблицей, которая будет связана с `game_object_component_prototypes`. Драфт:
![image](https://user-images.githubusercontent.com/1573467/135266328-5184bdad-0ae0-40d6-8d00-7df09be1e592.png)

![image](https://user-images.githubusercontent.com/1573467/135266401-b8254620-8404-4e3a-b014-313d9ef9aa9d.png)

Так как это полу-статические данные (справочные), то их изменения в рантайме не ожидается, ввиду чего можно засунуть все это дело в json, при этом сохранив возможность ориентации внутри, например:
```SQL
select 
	component_data.data->'hp' hp, 
	component_data.data->'maxHp' max_hp, 
	component_data.data->'someObject'->>'field' some_field
from game_object_component_prototype_data component_data 
join game_object_component_prototypes component on component.id = component_data.component_id 
join game_object_prototypes game_object on game_object.id = component.prototype_id
where game_object.id = 1
```

```
 hp | max_hp | some_field
----+--------+------------
 10 | 10     | data
(1 row)
```

Таким образом прототипы можно генерировать на стороне клиента, либо, вообще в отдельном тулсете в виде json и в последствии, через эволюцию, загружать/обновлять их.
Маппинг с JSON в модель должен проходить хорошо и гладко, для специфичных типов можно написать свои сериализаторы/десериализаторы.

**Требуется сделать**:
1. Создать табличку `game_object_component_prototype_datas` и сущность
2.

**Comment by Empericall** [comment]
1. Могут ли некоторые компоненты быть переиспользованы в рамках разных прототипов?

Например:
```
----------------------------------
| component_id |       data      |
----------------------------------
|      1       | {"key1":"val1"} |
|      2       | {"key2":"val2"} |
----------------------------------
```

```
-------------------------------
| prototype_id | component_id |
-------------------------------
|      1       |      1       | <--- ???
|      1       |      2       |
|      2       |      1       | <--- ???
-------------------------------
```

- Если да, то необходимо отделять связь между прототипами и компонентами за рамки декларативной таблицы компонентов.
- Если нет, то можно связывать прототипы с компонентами в рамках одной таблицы (декларативной).

P.S. Моё мнение: да, могут быть.

2. Может ли возникать наличие нескольких записей с json данными для этого и того же компонента.

Например:
```
----------------------------------
| component_id |       data      |
----------------------------------
|      1       | {"key1":"val1"} | <---- ???
|      1       | {"key11":"val1"}| <---- ???
|      2       | {"key2":"val2"} |
|      3       | {"key3":"val3"} |
----------------------------------
```

- Если да, то необходимо вынести component_data в отдельную таблицу, а со стороны сервисной части мерджить полученные
мапы (но трудно представить что будет с большой вложенностью одновременно с наличием комплексных типов).
- Если нет, то колонка component_data может находиться в таблице components.

P.S. Моё мнение: в этом вопросе здесь всё зависит от желания заёбываться с логикой мерджа N-ного количества
таких возможных записей. Мне кажется будет проще предусмотреть этот момент в тулинге, который будет необходим
для генерации эволюций (если он будет выполнен в виде api, то придумывать даже ничего не придётся) и crud части
персистенции (но я могу ошибаться на счёт того что 1ый вариант является проблемным).
